spring:
  application:
    name: S3 Upload Service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/file-mirror-upload}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: file-mirror-status-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.aniket.mirror.events

  jackson:
    use-jackson2-defaults: true

server:
  servlet:
    context-path: /api
  port: ${SERVER_PORT:8081}

aws:
  s3:
    bucket: ${S3_BUCKET:amzn-file-mirror-bucket}
  region: ${AWS_REGION:ap-south-1}

mirror:
  kafka:
    file-upload-topic: file_upload
    file-mirrored-topic: file_mirrored
    file-mirror-check-topic: file_mirror_check
